import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProductListingPage from "@/components/PokemonList/PokemonList";
// import UserList from "../components/Users/Users";
import Footer from "@/components/Footer/footer";
import Counter from "@/components/Counter/Counter";
import Header from "@/components/Header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Header />
    </html>
  );
}
